/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	versioned "github.com/quobyte/k8s-operator/pkg/kubernetes-actors/clientset/versioned"
	internalinterfaces "github.com/quobyte/k8s-operator/pkg/kubernetes-actors/informers/externalversions/internalinterfaces"

	quobyte_com_v1 "github.com/quobyte/k8s-operator/pkg/api/quobyte.com/v1"
	v1 "github.com/quobyte/k8s-operator/pkg/kubernetes-actors/listers/quobyte.com/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// QuobyteServiceInformer provides access to a shared informer and lister for
// QuobyteServices.
type QuobyteServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.QuobyteServiceLister
}

type quobyteServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewQuobyteServiceInformer constructs a new informer for QuobyteService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewQuobyteServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredQuobyteServiceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredQuobyteServiceInformer constructs a new informer for QuobyteService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredQuobyteServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.QuobyteV1().QuobyteServices(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.QuobyteV1().QuobyteServices(namespace).Watch(options)
			},
		},
		&quobyte_com_v1.QuobyteService{},
		resyncPeriod,
		indexers,
	)
}

func (f *quobyteServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredQuobyteServiceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *quobyteServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&quobyte_com_v1.QuobyteService{}, f.defaultInformer)
}

func (f *quobyteServiceInformer) Lister() v1.QuobyteServiceLister {
	return v1.NewQuobyteServiceLister(f.Informer().GetIndexer())
}
